{% set name = "marimo-labs" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/marimo_labs-{{ version }}.tar.gz
    sha256: 05f0f2db8f8c984089d4d50d98fbc8c24f6d2df42bafcc5bf38c18124de85033
  # TODO: remove on next release
  - url: https://raw.githubusercontent.com/marimo-team/marimo-labs/main/LICENSE
    sha256: cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - marimo >=0.3.8
    - huggingface_hub >=0.19.3
    - requests >=2.0
    - pyyaml >=5.0
    - pillow >=7.0
    - numpy >=1.21.0

test:
  imports:
    - marimo_labs
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Cutting-edge experimental features for marimo
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/marimo-team/marimo-labs
  dev_url: https://github.com/marimo-team/marimo-labs

extra:
  recipe-maintainers:
    - pavelzw
